.PHONY: clean All

All:
	@echo "----------Building project:[ LunarMagicSign - Release ]----------"
	@$(MAKE) -f  "LunarMagicSign.mk"
clean:
	@echo "----------Cleaning project:[ LunarMagicSign - Release ]----------"
	@$(MAKE) -f  "LunarMagicSign.mk" clean
